name: Build Windows Executable

# Trigger the workflow when you push a tag (e.g. v1.0.0)
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Build Dependencies
      run: |
        pip install --upgrade pip
        pip install pyinstaller gdown

    - name: Build Executable with PyInstaller
      run: |
        pyinstaller --onefile --name gdown.exe gdownpython.py
      # This assumes you have a wrapper script (gdown_wrapper.py) that calls gdown's main,
      # for example:
      #   from gdown.__main__ import main
      #   if __name__ == "__main__":
      #       main()

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windows Artifact
      uses: softprops/action-gh-release@v1
      with:
        files: dist\gdown_exe.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
