name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.8"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
 
      - name: Install Make (Windows only)
        if: matrix.os == 'windows-latest'
        run: choco install make
 
      - name: Install Package for Testing
        run: pip install .[test]
 
      - name: Lint
        if: matrix.os != 'windows-latest'
        run: make lint
 
      - name: Test
        run: make test
 
      - name: Build Distribution and Install from Dist
        shell: bash
        run: |
          make build
          pip install dist/gdown-*.tar.gz
          pip install dist/gdown-*.whl
 
      - name: Install PyInstaller (Windows only)
        if: matrix.os == 'windows-latest'
        run: pip install pyinstaller
 
      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile --name gdown.exe gdownpython.py
          dir dist
 
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: gdown-artifacts-${{ matrix.os }}
          path: dist/

  release:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Download the Windows artifact. This will download into "./dist/gdown-artifacts-windows-latest"
      - name: Download Windows build artifact
        uses: actions/download-artifact@v4
        with:
          name: gdown-artifacts-windows-latest
          path: ./dist

      - name: Create Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag "v${{ github.run_number }}"
          git push origin "v${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Create Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: "v${{ github.run_number }}"
          title: "Release v${{ github.run_number }}"
          workdir: "./dist/gdown-artifacts-windows-latest/"
          prerelease: "false"
